id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-05-24T20:20:07.411Z
blockData:
  top: 48
  left: 48
  uuid: 046380f2-cf3d-4244-9449-0f0ca5c53b43
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
