id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-05-24T21:13:21.187Z
blockData:
  top: 48
  left: 48
  uuid: 05a9329b-ce03-4984-829b-abcb1d2adbfa
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
