id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-05-24T20:31:26.168Z
blockData:
  top: 48
  left: 48
  uuid: be9065e0-aacd-4bff-b508-e28ff9a8c68b
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
